all: cliente servidor

cliente: business/PDU.java client/Cliente.java
	javac business/PDU.java
	javac client/Cliente.java

servidor: servidor/Servidor.java servidor/ServidorThread.java
	javac servidor/Servidor.java
	javac servidor/ServidorThread.java